name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.1.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_TOKEN }}
          

    - name: Build and Push Docker rancher/k3s Image
      working-directory: ./
      run: |
        docker build -t rancher-k3s .
        docker tag rancher-k3s sysperu/rancher-k3s
        docker push sysperu/rancher-k3s